Feature/ubi 245/gke deployment
Ubivius/telemetry-prometheus pull request #1
Opened 2021-02-21 19:02 UTC by MaximeStOnge

#### What changes does this PR contain?
Resources override and Readme

#### Which JIRA ticket ID's are associated with this PR?
UBI-245

#### Additional comments and information

2021-02-21 20:34 UTC, ysma500 requested changes

2021-02-21 20:34 UTC, ysma500 commented on chart/values.yaml
> +    limits:
Req first

2021-02-21 20:34 UTC, ysma500 commented on chart/values.yaml
> +    limits:
Req first

2021-02-21 20:34 UTC, ysma500 commented on chart/values.yaml
> +      limits:
Req first

2021-02-21 20:34 UTC, ysma500 commented on chart/values.yaml
> +    limits:
Req first

2021-02-21 20:34 UTC, ysma500 commented on chart/values.yaml
> +      memory: 32Mi
New line EOF missing

2021-02-21 23:06 UTC, ysma500 approved these changes

2021-02-22 23:13 UTC, ArcticWalrus approved these changes

2021-02-22 23:13 UTC, merged